name: Build and Release the Serverless Azure Java Agent
on:
  push:
    tags:
      - "dd-serverless-azure-java-agent-**"

jobs:
  build:
    name: Build Serverless Azure Java Agent
    runs-on: ubuntu-latest
    outputs:
      mini-agent-version: ${{ steps.get-serverless-mini-agent.outputs.mini_agent_version }}
    steps:
      - run: echo ${{ github.ref_name }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Serverless Mini Agent
        id: get-serverless-mini-agent
        run: |
          LIBDATADOG_RESPONSE=$(curl -s "https://api.github.com/repos/datadog/libdatadog/releases")
          MINI_AGENT_VERSION=$(echo "$LIBDATADOG_RESPONSE" | jq -r --arg pattern "sls-v[0-9]*\.[0-9]*\.[0-9]*" '.[] | select(.tag_name | test($pattern)) | .tag_name' | sort -V | tail -n 1)

          echo "Using version ${MINI_AGENT_VERSION} of mini agent"
          echo "mini_agent_version=$(echo "$MINI_AGENT_VERSION" | jq -rR 'ltrimstr("sls-")')" >> "$GITHUB_OUTPUT"

          curl --output-dir ./temp/ --create-dirs -O -s -L "https://github.com/DataDog/libdatadog/releases/download/${MINI_AGENT_VERSION}/datadog-serverless-agent.zip"
          unzip ./temp/datadog-serverless-agent.zip -d ./temp/datadog-serverless-agent

          mkdir src/main/resources
          cp ./temp/datadog-serverless-agent/datadog-serverless-agent-linux-amd64/datadog-serverless-trace-mini-agent src/main/resources/datadog-serverless-trace-mini-agent
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build dd-serverless-azure-java-agent jar
        run: ./build.sh
      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: target/${{ github.ref_name }}-jar-with-dependencies.jar
  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    env:
      MINI_AGENT_VERSION: ${{ needs.build.outputs.mini-agent-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
      - name: Rename artifacts
        run: |
          cp release/${{ github.ref_name }}-jar-with-dependencies.jar release/${{ github.ref_name }}.jar
          cp release/${{ github.ref_name }}-jar-with-dependencies.jar release/dd-serverless-azure-java-agent.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Uses [${{ env.MINI_AGENT_VERSION }}](https://github.com/DataDog/libdatadog/releases/tag/sls-${{ env.MINI_AGENT_VERSION }}) of the Serverless Mini Agent."
          draft: true
          generate_release_notes: true
          make_latest: true
          files: |
            release/${{ github.ref_name }}.jar
            release/dd-serverless-azure-java-agent.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest
          tag_name: download-latest
          body: "This release tracks the latest version available, currently **${{ github.ref_name }}**."
          files: release/dd-serverless-azure-java-agent.jar
